import { Property, Agent, Testimonial } from './types';

export const AGENTS: Agent[] = [
    {
        id: 1,
        name: 'Prateek Gupta',
        title: 'Co-Founder',
        image: '/images/prateek.png',
        linkedin: '#',
        email: 'mailto:pratik.gupta@nestingglobal.com'
    },
    {
        id: 3,
        name: 'Raghvendra Singh',
        title: 'Co-Founder',
        image: '/images/Raghvendra.png',
        linkedin: '#',
        email: 'mailto:raghvendra.singh@nestingglobal.com'
    },
    {
        id: 2,
        name: 'Vaishali Arora',
        title: 'Director',
        image: '/images/Vaishali.png',
        linkedin: '#',
        email: 'mailto:vaishali.arora@nestingglobal.com'
    }
];

export const PROPERTIES: Property[] = [
  {
    id: 'p1',
    title: 'Opulent Penthouse in Burj Khalifa',
    location: 'Downtown Dubai',
    price: 35000000,
    bedrooms: 5,
    bathrooms: 6,
    area: 7500,
    type: 'Penthouse',
    status: 'Featured',
    images: [
      '/property image/dubaiii.jpg',
      '/property image/dubaii.jpg',
      '/property image/dubais.jpg',
      '/property image/pent house.jpg',
    ],
    description: 'Experience unparalleled luxury in this breathtaking penthouse at the iconic Burj Khalifa. Offering 360-degree views of Dubai, this residence is the epitome of high-end living with bespoke interiors and world-class amenities.',
    amenities: ['Private Cinema', 'Infinity Pool', 'Smart Home System', '24/7 Concierge', 'Valet Parking', 'Direct Mall Access'],
    agent: { name: AGENTS[0].name, image: AGENTS[0].image },
    coordinates: { lat: 25.1972, lng: 55.2744 },
  },
  {
    id: 'p2',
    title: 'Signature Villa on The Palm Jumeirah',
    location: 'Palm Jumeirah',
    price: 55000000,
    bedrooms: 6,
    bathrooms: 7,
    area: 12000,
    type: 'Villa',
    status: 'New',
    images: [
      '/property image/luxury-apartments-for-sale-in-dubai.webp',
      '/property image/dubai flats.jpg',
      '/property image/download.jpg',
    ],
    description: 'A masterpiece of architectural design, this beachfront villa offers a private beach, stunning sea views, and ultimate privacy. Featuring custom Italian furniture, a private gym, and lush landscaped gardens.',
    amenities: ['Private Beach Access', 'Sea View', 'Landscaped Garden', 'Private Gym', 'Outdoor Kitchen', 'Maid\'s Room'],
    agent: { name: AGENTS[2].name, image: AGENTS[2].image },
    coordinates: { lat: 25.1111, lng: 55.1396 },
  },
  {
    id: 'p3',
    title: 'Modern Apartment with Marina Views',
    location: 'Dubai Marina',
    price: 5200000,
    bedrooms: 3,
    bathrooms: 4,
    area: 2200,
    type: 'Apartment',
    status: 'For Sale',
    images: [
      '/property image/dubais.jpg',
      '/property image/dubaii.jpg',
    ],
    description: 'Chic and contemporary apartment in the heart of Dubai Marina. Floor-to-ceiling windows provide spectacular views of the marina and the sea. Located in a prestigious tower with state-of-the-art facilities.',
    amenities: ['Full Marina View', 'Shared Gym', 'Infinity Pool', 'Children\'s Play Area', '24/7 Security', 'Close to Metro'],
    agent: { name: AGENTS[1].name, image: AGENTS[1].image },
    coordinates: { lat: 25.0784, lng: 55.1399 },
  },
  {
    id: 'p4',
    title: 'Exclusive Mansion in Arabian Ranches',
    location: 'Arabian Ranches',
    price: 28000000,
    bedrooms: 7,
    bathrooms: 8,
    area: 15000,
    type: 'Villa',
    status: 'Featured',
    images: [
      '/property image/dubai flats.jpg',
      '/property image/download.jpg',
      '/property image/dubaii.jpg',
    ],
    description: 'A sprawling mansion in the tranquil Arabian Ranches community. Perfect for families, this home sits on a large plot with a private pool, entertainment areas, and overlooks the golf course.',
    amenities: ['Golf Course View', 'Private Landscaped Garden', 'Large Private Pool', 'BBQ Area', 'Driver\'s Room', 'Gourmet Kitchen'],
    agent: { name: AGENTS[2].name, image: AGENTS[2].image },
    coordinates: { lat: 25.0489, lng: 55.2721 },
  },
  {
    id: 'p5',
    title: 'Canal View Penthouse',
    location: 'Business Bay',
    price: 12500000,
    bedrooms: 4,
    bathrooms: 5,
    area: 4800,
    type: 'Penthouse',
    status: 'For Sale',
    images: [
      '/property image/pent house.jpg',
      '/property image/dubaiii.jpg',
    ],
    description: 'This duplex penthouse offers stunning views of the Dubai Water Canal and the city skyline. With a spacious terrace and modern finishes, it provides a luxurious urban lifestyle.',
    amenities: ['Canal View', 'Rooftop Terrace', 'Shared Gym', 'Sauna & Steam Room', 'Business Lounge', 'Valet Parking'],
    agent: { name: AGENTS[0].name, image: AGENTS[0].image },
    coordinates: { lat: 25.1853, lng: 55.2711 },
  },
  {
    id: 'p6',
    title: 'Luxury Apartment at JBR',
    location: 'Jumeirah Beach Residence',
    price: 6800000,
    bedrooms: 2,
    bathrooms: 3,
    area: 1900,
    type: 'Apartment',
    status: 'New',
    images: [
      '/property image/dubaii.jpg',
      '/property image/dubais.jpg',
    ],
    description: 'A beautifully furnished apartment just steps away from the beach at JBR. Enjoy a vibrant lifestyle with restaurants, cafes, and entertainment options at your doorstep.',
    amenities: ['Partial Sea View', 'Beach Access', 'Shared Pool', 'Modern Gym', 'High Floor', 'Retail Outlets'],
    agent: { name: AGENTS[1].name, image: AGENTS[1].image },
    coordinates: { lat: 25.0772, lng: 55.1325 },
  },
  {
    id: 'p7',
    title: 'Off-Plan Waterfront Residence',
    location: 'Emaar Beachfront',
    price: 8100000,
    bedrooms: 3,
    bathrooms: 4,
    area: 2100,
    type: 'Off-Plan',
    status: 'For Sale',
    images: [
      '/property image/download.jpg',
      '/property image/dubaiii.jpg',
    ],
    description: 'Invest in the future of Dubai with this off-plan apartment at Emaar Beachfront. A premium seaside community with private beach access and views of the Dubai Marina and the Arabian Gulf.',
    amenities: ['Private Beach', 'Palm Jumeirah View', 'Community Park', 'Yacht Club Access', 'Flexible Payment Plan', 'High ROI Potential'],
    agent: { name: AGENTS[0].name, image: AGENTS[0].image },
    coordinates: { lat: 25.0933, lng: 55.1332 },
  },
  {
    id: 'p8',
    title: 'Sky Collection Penthouse',
    location: 'Downtown Dubai',
    price: 42000000,
    bedrooms: 4,
    bathrooms: 5,
    area: 6000,
    type: 'Penthouse',
    status: 'Featured',
    images: [
      '/property image/dubaiii.jpg',
      '/property image/dubai flats.jpg',
    ],
    description: 'Part of an exclusive Sky Collection, this full-floor penthouse boasts panoramic views of the Dubai Fountain and Burj Khalifa. Exquisite finishes and unparalleled luxury await.',
    amenities: ['Fountain View', 'Private Elevator', 'Library', 'Home Automation', 'Cigar Lounge', 'Rooftop Pool'],
    agent: { name: AGENTS[0].name, image: AGENTS[0].image },
    coordinates: { lat: 25.1948, lng: 55.2769 },
  },
  {
    id: 'p9',
    title: 'Beachfront Villa with Atlantis View',
    location: 'Palm Jumeirah',
    price: 78000000,
    bedrooms: 7,
    bathrooms: 9,
    area: 14500,
    type: 'Villa',
    status: 'New',
    images: [
      '/property image/luxury-apartments-for-sale-in-dubai.webp',
      '/property image/pent house.jpg',
      '/property image/dubais.jpg',
    ],
    description: 'An architectural marvel on the exclusive Frond G of Palm Jumeirah. This custom-built villa offers breathtaking views of Atlantis The Royal, a private infinity pool, and direct beach access.',
    amenities: ['Full Atlantis View', 'Private Beach', 'Infinity Edge Pool', 'Basement Parking', 'Home Cinema', 'Staff Quarters'],
    agent: { name: AGENTS[2].name, image: AGENTS[2].image },
    coordinates: { lat: 25.1221, lng: 55.1500 },
  },
];

export const TESTIMONIALS: Testimonial[] = [
    {
        id: 1,
        name: 'The Al-Futtaim Family',
        location: 'Dubai, UAE',
        image: 'https://picsum.photos/seed/client1/150/150',
        quote: 'Nesting Global found us our dream villa on the Palm. Their professionalism and deep market knowledge are unmatched. The entire process was seamless and luxurious.',
        rating: 5
    },
    {
        id: 2,
        name: 'Mr. David Chen',
        location: 'Shanghai, China',
        image: 'https://picsum.photos/seed/client2/150/150',
        quote: 'As an international investor, I needed an agency I could trust. Nesting Global\'s team provided exceptional service, guiding me to a high-yield property in Downtown.',
        rating: 5
    },
    {
        id: 3,
        name: 'Sophia Lorenzi',
        location: 'Milan, Italy',
        image: 'https://picsum.photos/seed/client3/150/150',
        quote: 'The attention to detail and personalized service was extraordinary. They understood my aesthetic and found an apartment that felt like home instantly.',
        rating: 5
    }
];